// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgccjvoedbbsjqzchtmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnY2Nqdm9lZGJic2pxemNodG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMTA5MzMsImV4cCI6MjA3MjU4NjkzM30.ccdSAioLunlGaeQkZ0_WkxJ0_YhRXWOSUPGz2s8p434";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});